#!/bin/bash

echo "🔄 Restarting OpenCode with updated plugin..."
echo ""
echo "Steps to test the fix:"
echo "1. Close OpenCode completely (Ctrl+C or close the window)"
echo "2. Start OpenCode again:"
echo "   opencode"
echo "3. Re-authenticate with Qwen:"
echo "   /connect"
echo "   Select 'Qwen Code (qwen.ai OAuth)'"
echo "   Complete the browser authentication"
echo "4. Try sending a message"
echo ""
echo "5. Check if API key is being used:"
echo "   tail -50 ~/.config/opencode/logs/qwen-oauth.log | grep 'api_key\\|has_api_key'"
echo ""
echo "If you still see errors, run with debug mode:"
echo "   QWEN_OAUTH_DEBUG=true opencode"
